service: disasterops-core-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64 # Use arm64 for better performance and cost efficiency
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    format: esm
    banner: # Inject a runtime “require” shim into the ES Module bundle
      js: |
        import { createRequire } from 'module';
        const require = createRequire(import.meta.url);

package:
  patterns:
    - '!**/*.md'
    - '!**/*.test.*'
    - '!**/docs/**'
    - '!node_modules/**'
    - '!archive/**'
    - '!api-tests/**'
    - '!.github/**'
    - '!logs/**'

custom:
  dotenv:
    path: ./.env
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

functions:
  app:
    handler: src/index.handler
    events:
      - httpApi: '*'
